# theme: jekyll-theme-minimal
# theme: jekyll-theme-midnight
# theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Indian Maker Space
description: The companion website for the IMS Discord 