# Quickstart for GitHub Pages - GitHub Enterprise Cloud Docs 
# https://docs.github.com/en/enterprise-cloud@latest/pages/quickstart  
# Supported themes | GitHub Pages 
# https://pages.github.com/themes/
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

# theme: jekyll-theme-minimal

# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Indian Maker Space
description: The companion website for the IMS Discord 